const KEY='shd-chairkeeper-demo-v093';
const seed={requests:[],needs:[{id:'n1',name:'Unknown',note:'Photo note says: “shorter next time, maybe chrome.”',tags:['shorter','chrome'],created:'Demo sample'}],clients:[{id:'c1',name:'Kayla R.',phone:'(806) 555-0191',service:'Gel Manicure',likes:['almond','soft pink','thin French lines'],avoid:['heavy glitter'],future:['birthday chrome set'],visits:[{date:'Aug 12',service:'Gel Manicure',note:'Soft pink almond. Loved the shape.',tags:['almond','pink']}]},{id:'c2',name:'Sarah J.',phone:'(806) 555-0168',service:'Acrylic Full Set',likes:['medium almond','chrome'],avoid:['extra long'],future:['black + gold Halloween'],visits:[{date:'Aug 19',service:'Acrylic Full Set',note:'Pink chrome, medium almond.',tags:['pink','chrome','almond']}]}]};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.clients?x:structuredClone(seed)}catch{return structuredClone(seed)}}let db=load();function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function switchView(owner){$('#customerView').classList.toggle('off',owner);$('#ownerView').classList.toggle('on',owner);$('#customerBtn').classList.toggle('active',!owner);$('#ownerBtn').classList.toggle('active',owner);if(owner)renderAll()}
$('#customerBtn').onclick=()=>switchView(false);$('#ownerBtn').onclick=()=>switchView(true);
$('#date').min=new Date().toISOString().slice(0,10);let d=new Date();d.setDate(d.getDate()+1);$('#date').value=d.toISOString().slice(0,10);
$('#bookingForm').onsubmit=e=>{e.preventDefault();const req={id:'R'+Math.random().toString(36).slice(2,7).toUpperCase(),name:$('#name').value.trim(),phone:$('#phone').value.trim(),service:$('#service').value,date:$('#date').value,time:$('#time').value,shape:$('#shape').value,length:$('#length').value,note:$('#note').value.trim(),photo:$('#inspo').files.length?'1 inspiration photo':'none',status:'Awaiting',created:new Date().toLocaleString()};db.requests.unshift(req);save();$('#success').classList.remove('hide');$('#confirmText').textContent=`Demo request ${req.id} · ${req.name} · ${req.date} at ${req.time}`;e.target.reset();$('#date').value=d.toISOString().slice(0,10)};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');renderAll()});
function tagsFrom(t){const words=['almond','square','coffin','round','short','shorter','medium','long','pink','blue','green','sage','black','gold','chrome','french','glitter','floral','halloween','birthday','repair','removal'];return words.filter(w=>t.toLowerCase().includes(w))}
function parse(){const note=$('#parseNote').value.trim(),name=$('#parseName').value.trim();if(!note){$('#parseResult').innerHTML='<b>Add a note first.</b>';return}const tags=tagsFrom(note);const client=db.clients.find(c=>name&&c.name.toLowerCase()===name.toLowerCase());const likes=tags.filter(t=>['almond','square','coffin','round','pink','blue','green','sage','black','gold','chrome','french','floral'].includes(t));const avoid=/avoid|didn.t like|don't like|do not like/i.test(note)?tags:[];const future=/next time|wants|future|halloween|birthday/i.test(note)?note:'';const result={id:'N'+Date.now(),name:name||'Unknown',note,tags,likes,avoid,future,clientId:client?.id||null,created:new Date().toLocaleString()};db.needs.unshift(result);save();$('#parseResult').innerHTML=`<b>${client?'Likely route: '+esc(client.name):'Needs Me — client not deterministically matched'}</b><p>${esc(note)}</p><div>${tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')||'<span class="muted">No common nail tags detected</span>'}</div><p class="muted">Saved to Needs Me so a human decides before anything is filed.</p>`;$('#parseNote').value='';$('#parseName').value=''}
$('#parseBtn').onclick=parse;$('#quickAdd').onclick=()=>{switchView(true);$$('.tab')[0].click();$('#parseNote').focus()};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderNeeds(){const el=$('#needsList');if(!db.needs.length){el.innerHTML='<div class="item"><div><h4>All clear</h4><p>No unresolved demo items.</p></div></div>';return}el.innerHTML=db.needs.map(n=>`<div class="item"><div><h4>${esc(n.name||'Unknown')}</h4><p>${esc(n.note)}</p>${(n.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}<p>${esc(n.created||'')}</p></div><div class="actions">${db.clients.map(c=>`<button class="small good" onclick="fileNeed('${n.id}','${c.id}')">Save to ${esc(c.name)}</button>`).join('')}<button class="small" onclick="dismissNeed('${n.id}')">Dismiss</button></div></div>`).join('')}
window.dismissNeed=id=>{db.needs=db.needs.filter(n=>n.id!==id);save()};window.fileNeed=(nid,cid)=>{const n=db.needs.find(x=>x.id===nid),c=db.clients.find(x=>x.id===cid);if(!n||!c)return;c.visits.unshift({date:new Date().toLocaleDateString(),service:'Note / photo intake',note:n.note,tags:n.tags||[]});for(const t of n.likes||[])if(!c.likes.includes(t))c.likes.push(t);if(n.future&&!c.future.includes(n.future))c.future.push(n.future);db.needs=db.needs.filter(x=>x.id!==nid);save();selectClient(cid);$$('.tab').find(x=>x.dataset.tab==='clients').click()};
function renderRequests(){const el=$('#requestsList');if(!db.requests.length){el.innerHTML='<div class="item"><div><h4>No demo requests yet</h4><p>Switch to Customer Demo and submit one.</p></div></div>';return}el.innerHTML=db.requests.map(r=>`<div class="item"><div><h4>${esc(r.name)} · ${esc(r.service)}</h4><p>${esc(r.date)} · ${esc(r.time)} · ${esc(r.phone)}</p><p>${esc(r.shape)} · ${esc(r.length)}${r.note?' · '+esc(r.note):''}</p><span class="tag">${esc(r.status)}</span>${r.photo!=='none'?'<span class="tag">photo attached</span>':''}</div><div class="actions"><button class="small good" onclick="setReq('${r.id}','Confirmed')">Confirm</button><button class="small warn" onclick="setReq('${r.id}','Needs follow-up')">Follow up</button><button class="small" onclick="setReq('${r.id}','Archived')">Archive</button></div></div>`).join('')}
window.setReq=(id,status)=>{const r=db.requests.find(x=>x.id===id);if(r)r.status=status;save()};
let selectedClient=null;function renderClients(){const q=($('#clientSearch').value||'').toLowerCase();const list=db.clients.filter(c=>JSON.stringify(c).toLowerCase().includes(q));$('#clientButtons').innerHTML=list.map(c=>`<button class="${selectedClient===c.id?'active':''}" onclick="selectClient('${c.id}')"><b>${esc(c.name)}</b><br><span class="muted">${esc(c.service)} · ${esc(c.phone)}</span></button>`).join('');if(selectedClient)selectClient(selectedClient,true)}
window.selectClient=(id,noRender=false)=>{selectedClient=id;const c=db.clients.find(x=>x.id===id);if(!c)return;$('#clientDetail').innerHTML=`<h3>${esc(c.name)}</h3><p><b>${esc(c.phone)}</b> · usual: ${esc(c.service)}</p><h4>Recent work</h4><div class="photos"><div class="photo">💅</div><div class="photo">✨</div><div class="photo">🎨</div></div><h4>What we know</h4><p><b>Likes:</b> ${(c.likes||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')||'—'}</p><p><b>Avoid/change:</b> ${(c.avoid||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')||'—'}</p><p><b>Future ideas:</b> ${(c.future||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')||'—'}</p><h4>Visit history</h4>${(c.visits||[]).map(v=>`<div style="padding:11px 0;border-top:1px solid var(--line)"><b>${esc(v.date)} · ${esc(v.service)}</b><p class="muted">${esc(v.note)}</p>${(v.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`).join('')}`;if(!noRender)renderClients()};$('#clientSearch').oninput=renderClients;
function renderAll(){$('#needsCount').textContent=db.needs.length;$('#reqCount').textContent=db.requests.filter(r=>r.status!=='Archived').length;$('#clientCount').textContent=db.clients.length;renderNeeds();renderRequests();renderClients()}
$('#resetDemo').onclick=()=>{if(confirm('Reset all fake demo activity on this browser?')){db=structuredClone(seed);localStorage.removeItem(KEY);selectedClient=null;save()}};$('#copyBuild').onclick=async()=>{const x='Simply Hope Designs ChairKeeper v0.9.3 | Remote Demo | build v0.9.3-remote-demo | schema target 0006_v090_ai_intake_client_cards | 2026-08-24';try{await navigator.clipboard.writeText(x);alert('Build info copied.')}catch{prompt('Copy build info:',x)}};renderAll();
